Artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts
    source_url: 
    data_dir: artifacts/data_ingestion
    train_data_path: artifacts/data_ingestion
    test_data_path: artifacts/data_ingestion