Artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: https://github.com/Robin-star-lab/Fever_Medication/raw/refs/heads/main/enhanced_fever_medicine_recommendation%20(1).zip
    data_dir: artifacts/data_ingestion/fever_medic.zip
    unzipped_data: artifacts/data_ingestion
    train_data_path: artifacts/data_ingestion
    test_data_path: artifacts/data_ingestion


data_transformation:
    root_dir: artifacts/data_transformation
    data_path: artifacts/data_ingestion/enhanced_fever_medicine_recommendation.csv
    train_data_path: artifacts/data_transformation
    test_data_path: artifacts/data_transformation
    preprocessor_path: artifacts/data_transformation


model_training:
    root_dir: artifacts/model_training
    model_path: artifacts/model_training
    metrics_path: artifacts/model_training
    preprocessor_path: artifacts/data_transformation/preprocessor.pkl
    train_data_path: artifacts/data_transformation/train_data.csv


model_evaluation:
    root_dir: artifacts/model_evaluation
    model_path: artifacts/model_training/model.regressor
    metrics_path: artifacts/model_evaluation
    test_data_path: artifacts/data_transformation/test_data.csv